apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - name: primeiro-pv
        mountPath: /volume-container
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc-1

