apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - name: primeiro-volume
        mountPath: /volume-nginx
  - name: jenkins-container
    image: jenkins/jenkins:lts
    volumeMounts:
      - name: primeiro-volume
        mountPath: /volume-jenkins
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /home/thiago/primeiro-volume
        type: DirectoryOrCreate
